services:
    mysql:
        image: mysql:latest
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - dev
        volumes:
            - mysql:/var/lib/mysql
    grafana:
        image: grafana/grafana-enterprise
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: "2g"
                reservations:
                    cpus: "1"
                    memory: "1g"
        ports:
            - "3000:3000"
        networks:
            - dev
        volumes:
            - grafana-storage:/var/lib/grafana

    prometheus:
        image: prom/prometheus
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: "2g"
                reservations:
                    cpus: "1"
                    memory: "1g"
        ports:
            - "9090:9090"
        networks:
            - dev
        volumes:
            - prometheus:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: mssql
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: "2g"
                reservations:
                    cpus: "1"
                    memory: "1g"
        hostname: "mssql1"
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
        ports:
            - "1433:1433"
        networks:
            - default
        volumes:
            - mssql:/var/opt/mssql

    mongo-db:
        image: mongo
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: "2g"
                reservations:
                    cpus: "1"
                    memory: "1g"
        ports:
            - "27017:27017"
        networks:
            - default
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongoDB:/data/db
            - ./mongo:/etc/mongo

    mongo-express:
        image: mongo-express
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: "2g"
                reservations:
                    cpus: "1"
                    memory: "1g"
        ports:
            - "8081:8081"
        networks:
            - default
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo-db:27017/
            ME_CONFIG_BASICAUTH_ENABLED: true
            ME_CONFIG_BASICAUTH_USERNAME: express
            ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
        depends_on:
            - mongo-db

    redis:
        image: redis:latest
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: "2g"
                reservations:
                    cpus: "1"
                    memory: "1g"
        ports:
            - "6379:6379"
        networks:
            - dev
        volumes:
            - redis:/data
        command: redis-server --appendonly yes

    mailpit:
        image: axllent/mailpit
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: "2g"
                reservations:
                    cpus: "1"
                    memory: "1g"
        volumes:
            - mailpit:/data
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - dev
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
    mysql:
        driver: local
    mailpit:
        driver: local
    redis:
        driver: local
    grafana-storage:
        driver: local
    prometheus:
        driver: local
    mssql:
        driver: local
    mongoDB:
        driver: local

networks:
    default:
        driver: bridge
    dev:
        external: true
