services:
    pgsql:
        image: postgres
        restart: always
        mem_limit: "2g"
        ports:
            - "5432:5432"
        networks:
            - dev
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - pgsql:/var/lib/postgresql

    setup:
        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
        volumes:
            - ./elastic-search/certs:/usr/share/elasticsearch/config/certs
            - ./elastic-search/setup.sh:/usr/share/setup.sh:ro
        user: "0"
        environment:
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
            - KIBANA_PASSWORD=${KIBANA_PASSWORD}
        command: >
            bash -c '/usr/share/setup.sh'
        healthcheck:
            test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
            interval: 1s
            timeout: 5s
            retries: 120
        networks:
            - dev

    es01:
        depends_on:
            setup:
                condition: service_healthy
        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
        restart: always
        volumes:
            - ./elastic-search/certs:/usr/share/elasticsearch/config/certs
            - esdata01:/usr/share/elasticsearch/data
        ports:
            - ${ES_PORT}:9200
        environment:
            - node.name=es01
            - cluster.name=${CLUSTER_NAME}
            - cluster.initial_master_nodes=es01
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
            - bootstrap.memory_lock=true
            - xpack.security.enabled=true
            - xpack.security.http.ssl.enabled=true
            - xpack.security.http.ssl.key=certs/es01/es01.key
            - xpack.security.http.ssl.certificate=certs/es01/es01.crt
            - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
            - xpack.security.transport.ssl.enabled=true
            - xpack.security.transport.ssl.key=certs/es01/es01.key
            - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
            - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
            - xpack.security.transport.ssl.verification_mode=certificate
            - xpack.license.self_generated.type=${LICENSE}
            - xpack.ml.use_auto_machine_memory_percent=true
        mem_limit: ${MEM_LIMIT}
        ulimits:
            memlock:
                soft: -1
                hard: -1
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
                ]
            interval: 10s
            timeout: 10s
            retries: 120
        networks:
            - dev

    kibana:
        depends_on:
            es01:
                condition: service_healthy
        image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
        volumes:
            - ./elastic-search/certs:/usr/share/kibana/config/certs
            - kibanadata:/usr/share/kibana/data
        ports:
            - ${KIBANA_PORT}:5601
        environment:
            - SERVERNAME=kibana
            - ELASTICSEARCH_HOSTS=https://es01:9200
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
            - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
        mem_limit: ${MEM_LIMIT}
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
                ]
            interval: 10s
            timeout: 10s
            retries: 120
        networks:
            - dev

    jaeger:
        image: jaegertracing/jaeger:2.15.1
        restart: always
        mem_limit: 2g
        ports:
            - "16686:16686"
            - "5778:5778"
            - "9411:9411"
        networks:
            - dev
        environment:
            ELASTIC_USERNAME: ${ELASTIC_USERNAME}
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
        volumes:
            - "./jaeger/config.yaml:/usr/share/jaeger/config.yaml"
            - "./elastic-search/certs:/usr/share/jaeger/certs"
        command: ["--config", "/usr/share/jaeger/config.yaml"]
        depends_on:
            es01:
                condition: service_healthy

    otel:
        image: otel/opentelemetry-collector-contrib
        restart: always
        mem_limit: 1g
        user: "0"
        volumes:
            - ./otel/collector-config.yaml:/etc/otelcol-contrib/config.yaml
            - "./elastic-search/certs:/usr/share/otelcol-contrib/certs:ro"
        ports:
            - "4317:4317" # OTLP gRPC receiver
            - "4318:4318" # OTLP http receiver
        environment:
            ELASTIC_USERNAME: ${ELASTIC_USERNAME}
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
        networks:
            - dev
        depends_on:
            - jaeger

volumes:
    pgsql:
        driver: local
    esdata01:
        driver: local
    kibanadata:
        driver: local

networks:
    default:
        driver: bridge
    dev:
        external: true
