receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318
processors:
    batch:

exporters:
    otlphttp/jaeger:
        endpoint: "http://jaeger:4318"
    otlphttp/prometheus:
        endpoint: "http://prometheus:9090"

extensions:
    health_check:
        endpoint: 0.0.0.0:13133
    pprof:
        endpoint: 0.0.0.0:1777
    zpages:
        endpoint: 0.0.0.0:55679

service:
    extensions: [ health_check, pprof, zpages ]
    pipelines:
        traces:
            receivers: [ otlp ]
            processors: [ batch ]
            exporters: [ otlphttp/jaeger ]
        metrics:
            receivers: [ otlp ]
            processors: [ batch ]
            exporters: [ otlphttp/prometheus ]
